mywebapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
import allauth
from haystack.views import SearchView

urlpatterns = [
    url('accounts/', include('allauth.urls')),
    url(r'^polls/', include('polls.urls', namespace='polls'), name='polls'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index')
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->

    <title>{% block head_title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/webapps.ico' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
    {% block extra_head %}

    {% endblock %}

  </head>
  <body>

    {% block body %}

    {% if messages %}
    <div class="alert alert-success .alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <ul>
	  {% for message in messages %}
	      <li>{{message}}</li>
	  {% endfor %}
      </ul>
    </div>
    {% endif %}

    <!--<strong>Menu:</strong>-->
    <!--<ul>-->
	<!--{% if user.is_authenticated %}-->
	<!--<li><a href="{% url 'account_email' %}">Change E-mail</a></li>-->
	<!--<li><a href="{% url 'account_logout' %}">Sign Out</a></li>-->
	<!--{% else %}-->
	<!--<li><a href="{% url 'account_login' %}">Sign In</a></li>-->
	<!--<li><a href="{% url 'account_signup' %}">Sign Up</a></li>-->
	<!--{% endif %}-->
      <!--</ul>-->


    <!-- 导航 -->
   <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li class="active"><a href="/">主页 </a></li>
        <!--<li><a href="#">Link</a></li>-->
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">One more separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>

      <form class="navbar-form navbar-left" >
        <div class="form-group">
          <input type="text" class="form-control" placeholder="搜索" disabled>
        </div>
        <button type="submit" class="btn btn-default" disabled>搜索</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'account_signup' %}">注册</a></li>
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->
        <li><a href="{% url 'account_login' %}">登录</a></li>
        {% else %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!--<li><a href="#" >设置</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="{% url 'account_logout' %}">登出</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    {% block base_content %}
    <h1>Hello, World!</h1>
    {% endblock %}

    {% endblock %}
    {% block extra_body %}
    {% endblock %}
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<footer class="container-fluid">
    <div class="card-body text-center px-0 f-16">
        <p class="card-text">Copyright&nbsp;&copy;&nbsp;2017-2018
            <a href="#" title="">Peijun</a>.&nbsp;Powered&nbsp;by&nbsp;Django.
        </p>
    </div>
</footer>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block head_title %}主页{% endblock %}
{% block base_content %}

<div class="container">
<div class="row">
  <div class="col-sm-6 col-md-4">
    <a href="{% url 'polls:index'%}" class="thumbnail">
      <img src="{% static 'img/investigate.jpg' %}" alt="调查问卷">
    </a>
    <h3 class="text-center">调查问卷</h3>
  </div>
</div>
</div>

{% endblock %}